# Generated by Django 5.2.7 on 2025-10-23 17:21

import core.models.images
import core.models.thumbnail
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingModel',
            fields=[
                ('status', models.CharField(choices=[('approved', 'Approved'), ('created', 'Created'), ('canceled', 'Canceled'), ('changed', 'Changed'), ('completed', 'Completed'), ('failed', 'Failed'), ('paid', 'Paid'), ('pay_later', 'Pay Later'), ('refunded', 'Refunded')], default='created', max_length=20)),
                ('booking_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('tour_date', models.DateField()),
                ('pick_up_time', models.CharField(max_length=5)),
                ('full_name', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=150)),
                ('phone', models.CharField(max_length=25)),
                ('adults', models.PositiveIntegerField(default=1)),
                ('children', models.PositiveIntegerField(blank=True, null=True)),
                ('hotel_name', models.CharField(max_length=150)),
                ('message', models.TextField(blank=True, default='', max_length=1000, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('selected_curreny', models.CharField(default='EUR', max_length=3)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'db_table': 'bookings',
                'ordering': ('-date_created',),
            },
        ),
        migrations.CreateModel(
            name='DayModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('number', models.PositiveSmallIntegerField(unique=True)),
            ],
            options={
                'db_table': 'days',
            },
        ),
        migrations.CreateModel(
            name='ExclusiveTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HighlightTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InclusiveTexts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PickupTimeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=5)),
            ],
            options={
                'db_table': 'times',
            },
        ),
        migrations.CreateModel(
            name='WhatBringModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WhatKnowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('created', 'Created'), ('failed', 'Failed'), ('pending', 'Pending'), ('paid', 'Paid'), ('refund', 'Refund')], default='created', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('iyzico', 'Iyzico'), ('paypal', 'Paypal')], default='cash', max_length=20)),
                ('payment_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payer_id', models.CharField(blank=True, max_length=128, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('booking_uuid', models.CharField(max_length=256)),
                ('tour_date', models.DateField()),
                ('customer_full_name', models.CharField(max_length=256)),
                ('customer_phone', models.CharField(max_length=256)),
                ('customer_email', models.CharField(max_length=256)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('booking', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bookingpayment', to='core.bookingmodel')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='TourModel',
            fields=[
                ('slug', models.SlugField(auto_created=True, max_length=355, unique=True)),
                ('tour_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('short_description', models.TextField(blank=True, max_length=1000, null=True)),
                ('full_description', models.TextField(blank=True, max_length=3000, null=True)),
                ('min_participant_for_a_booking', models.PositiveIntegerField(default=1, help_text='Bir rezervasyon için minimum katılımcı')),
                ('max_participants_for_a_booking', models.PositiveIntegerField(default=15, help_text='Bir rezervasyon için maximum katılımcı')),
                ('adult_age_start', models.PositiveIntegerField(default=12, help_text='Yetiskin yasi baslangic')),
                ('adult_age_end', models.PositiveIntegerField(default=99, help_text='Yetiskin yasi bitis')),
                ('adult_min_participant', models.PositiveIntegerField(default=1, help_text='Bir rezervasyonda kabul edilecek MINimum yetiskin sayisi')),
                ('adult_max_participant', models.PositiveIntegerField(default=10, help_text='Bir rezervasyonda kabul edilecek MAXimum yetiskin sayisi')),
                ('child_age_start', models.PositiveIntegerField(blank=True, default=3, help_text='Cocuk yasi baslangic', null=True)),
                ('child_age_end', models.PositiveIntegerField(blank=True, default=11, help_text='Cocuk yasi bitis', null=True)),
                ('child_min_participant', models.PositiveIntegerField(blank=True, default=0, help_text='Bir rezervasyonda kabul edilecek MINimum cocuk sayisi', null=True)),
                ('child_max_participant', models.PositiveIntegerField(blank=True, default=10, help_text='Bir rezervasyonda kabul edilecek MAXimum cocuk sayisi', null=True)),
                ('duration', models.CharField(default='6-7 hours', help_text='Tur suresi', max_length=255)),
                ('pickup_description', models.TextField(default='All hotels in Side area', max_length=2000)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField()),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('excluded', models.ManyToManyField(blank=True, to='core.exclusivetexts')),
                ('highlights', models.ManyToManyField(blank=True, to='core.highlighttexts')),
                ('included', models.ManyToManyField(blank=True, to='core.inclusivetexts')),
                ('what_to_bring', models.ManyToManyField(blank=True, to='core.whatbringmodel')),
                ('what_to_know', models.ManyToManyField(blank=True, to='core.whatknowmodel')),
            ],
            options={
                'verbose_name': 'Tour',
                'verbose_name_plural': 'Tours',
                'db_table': 'tours',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='ThumbnailModel',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=core.models.thumbnail.thumbnail_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=256, null=True)),
                ('tour', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tour_thumbnail', to='core.tourmodel')),
            ],
            options={
                'verbose_name': 'Thumbnail',
                'verbose_name_plural': 'Thumbnail',
                'db_table': 'thumbnail',
            },
        ),
        migrations.CreateModel(
            name='PeriodModel',
            fields=[
                ('period_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(default='High Season', max_length=300)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('adult_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('child_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('discount_rate', models.PositiveIntegerField(blank=True, help_text='indirim oranı tüm katılımcıların toplam rezervasyon tutarında yüzdelik olarak düşülücek.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('enabled_days', models.ManyToManyField(blank=True, to='core.daymodel')),
                ('pick_up_times', models.ManyToManyField(blank=True, to='core.pickuptimemodel')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_periods', to='core.tourmodel')),
            ],
            options={
                'verbose_name': 'Period',
                'verbose_name_plural': 'Periods',
                'db_table': 'periods',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('image_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('image', models.ImageField(upload_to=core.models.images.tour_image_upload_path)),
                ('alt_text', models.CharField(blank=True, max_length=256, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tour_images', to='core.tourmodel')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
                'db_table': 'images',
            },
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tourbookings', to='core.tourmodel'),
        ),
    ]
