# Generated by Django 5.2.7 on 2025-10-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmodel',
            name='slug',
            field=models.SlugField(auto_created=True, editable=False, max_length=355, unique=True),
        ),
    ]
