# Generated by Django 5.2.7 on 2025-10-31 10:07

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_tourmodel_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourmodel',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, max_length=355, populate_from='title', unique=True),
        ),
    ]
