# Generated by Django 5.2.7 on 2025-11-09 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_tourmodel_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourmodel',
            name='review_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tourmodel',
            name='review_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
