# Generated by Django 5.2.7 on 2025-11-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tourmodel_review_count_tourmodel_review_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodmodel',
            name='adult_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='periodmodel',
            name='child_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
