# Generated by Django 5.2.7 on 2025-11-17 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_periodmodel_adult_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingmodel',
            name='adult_price',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='child_price',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='discount_rate',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bookingmodel',
            name='period',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='periodbookings', to='core.periodmodel'),
        ),
        migrations.AlterField(
            model_name='bookingmodel',
            name='tour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tourbookings', to='core.tourmodel'),
        ),
    ]
